import numpy as np
import scipy as sp

from simulation import Field

class ScatteredField(Field):
    """
    A class representing the field generated by a set of scatterers.

    Attributes:
    scatterers: np.ndarray
        The positions of the scatterers. Must take the form [[x1, y1], [x2, y2], ...].
    E_0: float
        The amplitude of the incident field
    k_0: float
        The wavenumber of the incident field
    propagation_angle: float
        The angle of propagation of the incident field

    Methods:
    field(R: np.ndarray) -> np.ndarray
        Returns the field at the point R
    """
    def __init__(self, scatterers: np.ndarray, E_0, k_0, propagation_angle):
        super().__init__(E_0, k_0, propagation_angle)
        self.scatterers = scatterers

    def field(self, R: np.ndarray) -> np.ndarray:
        """
        This function generates the field created by the scatterering of an incident wave by n point like
        scatterers. It can generate fields for any number of scatterers.]

        Parameters:
        R: np.ndarray
            The point at which to calculate the field. Must take the form [x, y].

        Returns:
        np.ndarray
            The field at the point R. Takes the form [Ex, Ey].
        """

        N = len(self.scatterers)
        M = np.zeros((N, N), dtype=complex)
        EjCont = 0

        if N > 0:
            for i in range(0, N):
                for j in range(0, N):
                    if i == j:
                        M[i][j] = 1
                    else:
                        M[i][j] = sp.special.hankel1(0, self.k_0 * np.linalg.norm(np.subtract(self.scatterers[i], self.scatterers[j])))

            Ej = np.linalg.solve(M, self.v_incident(self.scatterers))

            for i in range(0, N):
                EjCont += sp.special.hankel1(0, self.k_0 * np.linalg.norm(np.subtract(R, self.scatterers[i]))) * Ej[i]

        return self.incident(R) + EjCont
    
